version: '3.3'

services:
  spotweb:
    build:
      context: .
      dockerfile: ./x86/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: spotweb
      MYSQL_PASSWORD: spotweb
      MYSQL_DATABASE: spotweb
    volumes_from:
      - spotweb-data:/var/lib/mysql

volumes:
  spotweb-data:
